# Generated by Django 6.0.4 on 2026-04-25 21:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('thinking_style', models.CharField(blank=True, max_length=100)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('preferred_domain', models.CharField(blank=True, max_length=200)),
                ('experience_level', models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=50)),
                ('experience_years', models.CharField(blank=True, max_length=10)),
                ('education', models.CharField(blank=True, choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD'), ('self_taught', 'Self-taught')], max_length=50)),
                ('current_status', models.CharField(blank=True, choices=[('student', 'Student'), ('employed', 'Employed'), ('freelance', 'Freelance'), ('unemployed', 'Unemployed'), ('career_break', 'Career Break')], max_length=50)),
                ('availability', models.CharField(blank=True, choices=[('lt5', '< 5 hrs/week'), ('5_10', '5–10 hrs/week'), ('10_20', '10–20 hrs/week'), ('gt20', '20+ hrs/week')], max_length=20)),
                ('goal', models.CharField(blank=True, choices=[('switch_domain', 'Switch Domain'), ('excel_current', 'Excel in Current Domain'), ('get_job', 'Get a Job'), ('promotion', 'Promotion'), ('side_income', 'Side Income')], max_length=50)),
                ('linkedin', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('profile_completion', models.IntegerField(default=0)),
                ('is_assessment_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
