# Generated by Django 6.0.4 on 2026-04-27 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('lt5', '< 5 hrs/week'), ('5_10', '5-10 hrs/week'), ('10_20', '10-20 hrs/week'), ('gt20', '20+ hrs/week')], max_length=20),
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('match_score', models.IntegerField(default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
    ]
