# Generated by Django 6.0.4 on 2026-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_availability_careerpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='market_demand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='risk_tolerance',
            field=models.CharField(blank=True, choices=[('low', 'Low — I prefer stability'), ('medium', 'Medium — Balanced approach'), ('high', 'High — I embrace challenges')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='side_income_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill_levels',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_salary',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
