# Generated by Django 6.0.4 on 2026-04-29 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_task_notes_remove_task_time_taken_tasklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['week_number', 'order', 'created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='resource_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_title', models.CharField(max_length=200)),
                ('total_weeks', models.IntegerField(default=12)),
                ('current_week', models.IntegerField(default=1)),
                ('phases', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_skills', models.JSONField(default=list)),
                ('required_skills', models.JSONField(default=list)),
                ('gap_skills', models.JSONField(default=list)),
                ('market_insights', models.JSONField(default=list)),
                ('job_market_data', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('career_options', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('goals', models.JSONField(default=list)),
                ('is_current', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_pct', models.IntegerField(default=0)),
                ('ai_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='dashboard.roadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('roadmap', 'week_number')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='weekly_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dashboard.weeklyplan'),
        ),
    ]
