# Generated by Django 6.0.4 on 2026-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_task_options_task_order_task_resource_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_skill',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='why_assigned',
            field=models.TextField(blank=True),
        ),
    ]
