# Generated by Django 6.0.4 on 2026-05-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgapanalysis',
            name='adzuna_jobs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='skillgapanalysis',
            name='adzuna_jobs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillgapanalysis',
            name='adzuna_market_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='skillgapanalysis',
            name='adzuna_role_searched',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='skillgapanalysis',
            name='adzuna_salary',
            field=models.JSONField(default=dict),
        ),
    ]
